FILE_NAME: twitterConfig_ninjathreeceeTwitterTest_01.yml
SCREEN_NAME: ninjathreecee
CONSUMER_KEY: KTDtT7IouFrskZBcjeI9x45kk
CONSUMER_SECRET: 6jHURX5dMx9ubXNZcMQ3qszAVPTyge4UK3YUPqvEKPw3dQfdF3
TOKEN: 1118058524-pjFKKdB1htLvyMLvuzzkjaOphewOcKUmj2VGVCR
TOKEN_SECRET: qT5RoHUgoE768ztcGO4EccrSf6HrxDHD075f4L41zxrme
HIGH_WATER: 0