FILE_NAME: twitterConfig_altthreecee00.yml
SCREEN_NAME: altthreecee00
OWNER_ID: 848591649575927810
CONSUMER_KEY: 0g1pAgIqe6f3LN9yjaPBGJcSL
CONSUMER_SECRET: op5mSFdo1jenyiTxFyED0yD2W1rmviq35qpVlgSSyIIlFPuBj7
TOKEN: 848591649575927810-g8Hx92DSSYk0yoN08KGRs6Fbc79yFXG
TOKEN_SECRET: MiQPSuEXlkYcinlSFdLFdbjPbtFanCtLf8o6sE9BFPyPI
HIGH_WATER: 0